<?php
return [
    'Friday\Base\Event' => __DIR__ . '/Base/Event.php',
    'Friday\Base\ArrayableInterface' => __DIR__ . '/Base/ArrayableInterface.php',
    'Friday\Base\BaseObject' => __DIR__ . '/Base/BaseObject.php',
    'Friday\Base\Behavior' => __DIR__ . '/Base/Behavior.php',
    'Friday\Base\Component' => __DIR__ . '/Base/Component.php',
    'Friday\Base\Module' => __DIR__ . '/Base/Module.php',
    'Friday\Base\AbstractApplication' => __DIR__ . '/Base/AbstractApplication.php',
    'Friday\Base\ConfigurableInterface' => __DIR__ . '/Base/ConfigurableInterface.php',
    'Friday\Base\Exception\ExceptionInterface' => __DIR__ . '/Base/Exception/ExceptionInterface.php',
    'Friday\Base\Exception\BadMethodCallException' => __DIR__ . '/Base/Exception/BadMethodCallException.php',
    'Friday\Base\Exception\InvalidArgumentException' => __DIR__ . '/Base/Exception/InvalidArgumentException.php',
    'Friday\Base\Exception\InvalidConfigException' => __DIR__ . '/Base/Exception/InvalidConfigException.php',
    'Friday\Base\Exception\PropertyAccessException' => __DIR__ . '/Base/Exception/PropertyAccessException.php',
    'Friday\Base\Exception\RuntimeException' => __DIR__ . '/Base/Exception/RuntimeException.php',
    'Friday\Base\Exception\UnknownClassException' => __DIR__ . '/Base/Exception/UnknownClassException.php',
    'Friday\Base\Exception\UnknownPropertyException' => __DIR__ . '/Base/Exception/UnknownPropertyException.php',

    'Friday\Helper\AliasHelper' => __DIR__ . '/Helper/AliasHelper.php',
    'Friday\Helper\ArrayHelper' => __DIR__ . '/Helper/ArrayHelper.php',

    'Friday\Di\Container' => __DIR__ . '/Di/Container.php',
    'Friday\Di\Instance' => __DIR__ . '/Di/Instance.php',
    'Friday\Di\ServiceLocator' => __DIR__ . '/Di/ServiceLocator.php',
    'Friday\Di\Exception\NotInstantiableException' => __DIR__ . '/Di/Exception/NotInstantiableException.php',

    'Friday\SocketServer\Server' => __DIR__ . '/SocketServer/Server.php',
    'Friday\SocketServer\Connection' => __DIR__ . '/SocketServer/Connection.php',
    'Friday\SocketServer\Exception\ConnectionException' => __DIR__ . '/SocketServer/Exception/ConnectionException.php',
    'Friday\SocketServer\Event\ConnectionEvent' => __DIR__ . '/SocketServer/Event/ConnectionEvent.php',
    'Friday\SocketServer\Event\ContentEvent' => __DIR__ . '/SocketServer/Event/ContentEvent.php',
    'Friday\SocketServer\Event\ErrorEvent' => __DIR__ . '/SocketServer/Event/ErrorEvent.php',

    'Friday\Stream\Buffer' => __DIR__ . '/Stream/Buffer.php',
    'Friday\Stream\BufferedSink' => __DIR__ . '/Stream/BufferedSink.php',
    'Friday\Stream\CompositeStream' => __DIR__ . '/Stream/CompositeStream.php',
    'Friday\Stream\DuplexStreamInterface' => __DIR__ . '/Stream/DuplexStreamInterface.php',
    'Friday\Stream\ReadableStream' => __DIR__ . '/Stream/ReadableStream.php',
    'Friday\Stream\ReadableStreamInterface' => __DIR__ . '/Stream/ReadableStreamInterface.php',
    'Friday\Stream\Stream' => __DIR__ . '/Stream/Stream.php',
    'Friday\Stream\ThroughStream' => __DIR__ . '/Stream/ThroughStream.php',
    'Friday\Stream\Util' => __DIR__ . '/Stream/Util.php',
    'Friday\Stream\WritableStream' => __DIR__ . '/Stream/WritableStream.php',
    'Friday\Stream\WritableStreamInterface' => __DIR__ . '/Stream/WritableStreamInterface.php',

    'Friday\Web\Application' => __DIR__ . '/Web/Application.php',
    'Friday\Web\Server' => __DIR__ . '/Web/Server.php',
    'Friday\Web\Request' => __DIR__ . '/Web/Request.php',
    'Friday\Web\Response' => __DIR__ . '/Web/Response.php',
    'Friday\Web\ResponseCodes' => __DIR__ . '/Web/ResponseCodes.php',
    'Friday\Web\RequestHeaderParser' => __DIR__ . '/Web/RequestHeaderParser.php',

    'Friday\EventLoop\NextTickQueue'      => __DIR__ . '/EventLoop/NextTickQueue.php',
    'Friday\EventLoop\FutureTickQueue'    => __DIR__ . '/EventLoop/FutureTickQueue.php',
    'Friday\EventLoop\LoopInterface'      => __DIR__ . '/EventLoop/LoopInterface.php',
    'Friday\EventLoop\StreamSelectLoop'   => __DIR__ . '/EventLoop/StreamSelectLoop.php',
    'Friday\EventLoop\Timer'              => __DIR__ . '/EventLoop/Timer.php',
    'Friday\EventLoop\Timers'             => __DIR__ . '/EventLoop/Timers.php',
    'Friday\EventLoop\TimerInterface'     => __DIR__ . '/EventLoop/TimerInterface.php',

];