<?php
return [
    'Friday\Base\Event' => __DIR__ . '/Base/Event.php',
    'Friday\Base\EventTrait' => __DIR__ . '/Base/EventTrait.php',
    'Friday\Base\ArrayableInterface' => __DIR__ . '/Base/ArrayableInterface.php',
    'Friday\Base\BaseObject' => __DIR__ . '/Base/BaseObject.php',
    'Friday\Base\Behavior' => __DIR__ . '/Base/Behavior.php',
    'Friday\Base\Component' => __DIR__ . '/Base/Component.php',
    'Friday\Base\Module' => __DIR__ . '/Base/Module.php',
    'Friday\Base\AbstractApplication' => __DIR__ . '/Base/AbstractApplication.php',
    'Friday\Base\ConfigurableInterface' => __DIR__ . '/Base/ConfigurableInterface.php',
    'Friday\Base\Exception\ExceptionInterface' => __DIR__ . '/Base/Exception/ExceptionInterface.php',
    'Friday\Base\Exception\BadMethodCallException' => __DIR__ . '/Base/Exception/BadMethodCallException.php',
    'Friday\Base\Exception\InvalidArgumentException' => __DIR__ . '/Base/Exception/InvalidArgumentException.php',
    'Friday\Base\Exception\InvalidConfigException' => __DIR__ . '/Base/Exception/InvalidConfigException.php',
    'Friday\Base\Exception\PropertyAccessException' => __DIR__ . '/Base/Exception/PropertyAccessException.php',
    'Friday\Base\Exception\RuntimeException' => __DIR__ . '/Base/Exception/RuntimeException.php',
    'Friday\Base\Exception\UnknownClassException' => __DIR__ . '/Base/Exception/UnknownClassException.php',
    'Friday\Base\Exception\UnknownPropertyException' => __DIR__ . '/Base/Exception/UnknownPropertyException.php',
    'Friday\Base\Exception\Exception' => __DIR__ . '/Base/Exception/Exception.php',
    'Friday\Base\Exception\ErrorException' => __DIR__ . '/Base/Exception/ErrorException.php',
    'Friday\Base\Exception\InvalidRouteException' => __DIR__ . '/Base/Exception/InvalidRouteException.php',

    'Friday\Helper\AliasHelper' => __DIR__ . '/Helper/AliasHelper.php',
    'Friday\Helper\ArrayHelper' => __DIR__ . '/Helper/ArrayHelper.php',
    'Friday\Helper\FileHelper' => __DIR__ . '/Helper/FileHelper.php',
    'Friday\Helper\StringHelper' => __DIR__ . '/Helper/StringHelper.php',

    'Friday\Di\Container' => __DIR__ . '/Di/Container.php',
    'Friday\Di\Instance' => __DIR__ . '/Di/Instance.php',
    'Friday\Di\ServiceLocator' => __DIR__ . '/Di/ServiceLocator.php',
    'Friday\Di\Exception\NotInstantiableException' => __DIR__ . '/Di/Exception/NotInstantiableException.php',

    'Friday\SocketServer\Server' => __DIR__ . '/SocketServer/Server.php',
    'Friday\SocketServer\Connection' => __DIR__ . '/SocketServer/Connection.php',
    'Friday\SocketServer\Exception\ConnectionException' => __DIR__ . '/SocketServer/Exception/ConnectionException.php',
    'Friday\SocketServer\Event\ConnectionEvent' => __DIR__ . '/SocketServer/Event/ConnectionEvent.php',
    'Friday\SocketServer\Event\ContentEvent' => __DIR__ . '/SocketServer/Event/ContentEvent.php',
    'Friday\SocketServer\Event\ErrorEvent' => __DIR__ . '/SocketServer/Event/ErrorEvent.php',

    'Friday\Stream\Buffer' => __DIR__ . '/Stream/Buffer.php',
    'Friday\Stream\BufferedSink' => __DIR__ . '/Stream/BufferedSink.php',
    'Friday\Stream\CompositeStream' => __DIR__ . '/Stream/CompositeStream.php',
    'Friday\Stream\DuplexStreamInterface' => __DIR__ . '/Stream/DuplexStreamInterface.php',
    'Friday\Stream\ReadableStream' => __DIR__ . '/Stream/ReadableStream.php',
    'Friday\Stream\ReadableStreamInterface' => __DIR__ . '/Stream/ReadableStreamInterface.php',
    'Friday\Stream\Stream' => __DIR__ . '/Stream/Stream.php',
    'Friday\Stream\ThroughStream' => __DIR__ . '/Stream/ThroughStream.php',
    'Friday\Stream\Util' => __DIR__ . '/Stream/Util.php',
    'Friday\Stream\WritableStream' => __DIR__ . '/Stream/WritableStream.php',
    'Friday\Stream\WritableStreamInterface' => __DIR__ . '/Stream/WritableStreamInterface.php',
    'Friday\Stream\Event\Event' => __DIR__ . '/Stream/Event/Event.php',
    'Friday\Stream\Event\ErrorEvent' => __DIR__ . '/Stream/Event/ErrorEvent.php',
    'Friday\Stream\Event\ContentEvent' => __DIR__ . '/Stream/Event/ContentEvent.php',

    'Friday\Web\Application' => __DIR__ . '/Web/Application.php',
    'Friday\Web\Server' => __DIR__ . '/Web/Server.php',
    'Friday\Web\Request' => __DIR__ . '/Web/Request.php',
    'Friday\Web\Response' => __DIR__ . '/Web/Response.php',
    'Friday\Web\HttpCodes' => __DIR__ . '/Web/HttpCodes.php',
    'Friday\Web\RequestHeaderParser' => __DIR__ . '/Web/RequestHeaderParser.php',
    'Friday\Web\ResponseFormatterInterface' => __DIR__ . '/Web/ResponseFormatterInterface.php',
    'Friday\Web\HeaderCollection' => __DIR__ . '/Web/HeaderCollection.php',
    'Friday\Web\CookieCollection' => __DIR__ . '/Web/CookieCollection.php',
    'Friday\Web\Cookie' => __DIR__ . '/Web/Cookie.php',
    'Friday\Web\UrlManager' => __DIR__ . '/Web/UrlManager.php',
    'Friday\Web\UrlRule' => __DIR__ . '/Web/UrlRule.php',
    'Friday\Web\UrlRuleInterface' => __DIR__ . '/Web/UrlRuleInterface.php',
    'Friday\Web\Controller' => __DIR__ . '/Web/Controller.php',
    'Friday\Web\ConnectionContext' => __DIR__ . '/Web/ConnectionContext.php',
    'Friday\Web\HttpException\HttpException' => __DIR__ . '/Web/HttpException/HttpException.php',
    'Friday\Web\HttpException\NotFoundHttpException' => __DIR__ . '/Web/HttpException/NotFoundHttpException.php',

    'Friday\Web\Event\RequestParsedEvent' => __DIR__ . '/Web/Event/RequestParsedEvent.php',
    'Friday\Web\Event\RequestEvent' => __DIR__ . '/Web/Event/RequestEvent.php',
    'Friday\Web\Event\ErrorEvent' => __DIR__ . '/Web/Event/ErrorEvent.php',

    'Friday\EventLoop\NextTickQueue' => __DIR__ . '/EventLoop/NextTickQueue.php',
    'Friday\EventLoop\FutureTickQueue' => __DIR__ . '/EventLoop/FutureTickQueue.php',
    'Friday\EventLoop\LoopInterface' => __DIR__ . '/EventLoop/LoopInterface.php',
    'Friday\EventLoop\StreamSelectLoop' => __DIR__ . '/EventLoop/StreamSelectLoop.php',
    'Friday\EventLoop\Timer' => __DIR__ . '/EventLoop/Timer.php',
    'Friday\EventLoop\Timers' => __DIR__ . '/EventLoop/Timers.php',
    'Friday\EventLoop\TimerInterface' => __DIR__ . '/EventLoop/TimerInterface.php',

    'Friday\FileSystem\WoolTrait' => __DIR__ . '/FileSystem/WoolTrait.php',
    'Friday\FileSystem\TypeDetectorInterface' => __DIR__ . '/FileSystem/TypeDetectorInterface.php',
    'Friday\FileSystem\ThrottledQueuedInvoker' => __DIR__ . '/FileSystem/ThrottledQueuedInvoker.php',
    'Friday\FileSystem\QueuedInvoker' => __DIR__ . '/FileSystem/QueuedInvoker.php',
    'Friday\FileSystem\QueuedCall' => __DIR__ . '/FileSystem/QueuedCall.php',
    'Friday\FileSystem\PermissionFlagResolver' => __DIR__ . '/FileSystem/PermissionFlagResolver.php',
    'Friday\FileSystem\PooledInvoker' => __DIR__ . '/FileSystem/PooledInvoker.php',
    'Friday\FileSystem\AdapterInterface' => __DIR__ . '/FileSystem/AdapterInterface.php',
    'Friday\FileSystem\CallInvokerInterface' => __DIR__ . '/FileSystem/CallInvokerInterface.php',
    'Friday\FileSystem\FileSystem' => __DIR__ . '/FileSystemFileSystem.php',
    'Friday\FileSystem\FileSystemInterface' => __DIR__ . '/FileSystem/FileSystemInterface.php',
    'Friday\FileSystem\FlagResolver' => __DIR__ . '/FileSystem/FlagResolver.php',
    'Friday\FileSystem\FlagResolverInterface' => __DIR__ . '/FileSystem/FlagResolverInterface.php',
    'Friday\FileSystem\InstantInvoker' => __DIR__ . '/FileSystem/InstantInvoker.php',
    'Friday\FileSystem\MappedTypeDetector' => __DIR__ . '/FileSystem/MappedTypeDetector.php',
    'Friday\FileSystem\ModeTypeDetector' => __DIR__ . '/FileSystem/ModeTypeDetector.php',
    'Friday\FileSystem\ObjectStream' => __DIR__ . '/FileSystem/ObjectStream.php',
    'Friday\FileSystem\ObjectStreamSink' => __DIR__ . '/FileSystem/ObjectStreamSink.php',
    'Friday\FileSystem\OpenFileLimiter' => __DIR__ . '/FileSystem/OpenFileLimiter.php',
    'Friday\FileSystem\Util' => __DIR__ . '/FileSystem/Util.php',

    'Friday\FileSystem\Exception\ArgsExceptionTrait' => __DIR__ . '/FileSystem/Exception/ArgsExceptionTrait.php',
    'Friday\FileSystem\Exception\NotSupportedException' => __DIR__ . '/FileSystem/Exception/NotSupportedException.php',
    'Friday\FileSystem\Exception\RuntimeException' => __DIR__ . '/FileSystem/Exception/RuntimeException.php',
    'Friday\FileSystem\Exception\UnexpectedValueException' => __DIR__ . '/FileSystem/Exception/UnexpectedValueException.php',


    'Friday\FileSystem\Node\Directory' => __DIR__ . '/FileSystem/Node/Directory.php',
    'Friday\FileSystem\Node\DirectoryInterface' => __DIR__ . '/FileSystem/Node/DirectoryInterface.php',
    'Friday\FileSystem\Node\File' => __DIR__ . '/FileSystem/Node/File.php',
    'Friday\FileSystem\Node\FileInterface' => __DIR__ . '/FileSystem/Node/FileInterface.php',
    'Friday\FileSystem\Node\GenericOperationInterface' => __DIR__ . '/FileSystem/Node/GenericOperationInterface.php',
    'Friday\FileSystem\Node\GenericOperationTrait' => __DIR__ . '/FileSystem/Node/GenericOperationTrait.php',
    'Friday\FileSystem\Node\Link' => __DIR__ . '/FileSystem/Node/Link.php',
    'Friday\FileSystem\Node\LinkInterface' => __DIR__ . '/FileSystem/Node/LinkInterface.php',
    'Friday\FileSystem\Node\NodeInterface' => __DIR__ . '/FileSystem/Node/NodeInterface.php',
    'Friday\FileSystem\Node\RecursiveInvoker' => __DIR__ . '/FileSystem/Node/RecursiveInvoker.php',


    'Friday\FileSystem\ChildProcess\Adapter' => __DIR__ . '/FileSystem/ChildProcess/Adapter.php',
    'Friday\FileSystem\ChildProcess\Process' => __DIR__ . '/FileSystem/ChildProcess/Process.php',

    'Friday\FileSystem\Stream\DuplexStream' => __DIR__ . '/FileSystem/Stream/DuplexStream.php',
    'Friday\FileSystem\Stream\GenericStreamInterface' => __DIR__ . '/FileSystem/Stream/GenericStreamInterface.php',
    'Friday\FileSystem\Stream\GenericStreamTrait' => __DIR__ . '/FileSystem/Stream/GenericStreamTrait.php',
    'Friday\FileSystem\Stream\ReadableStream' => __DIR__ . '/FileSystem/Stream/ReadableStream.php',
    'Friday\FileSystem\Stream\ReadableStreamTrait' => __DIR__ . '/FileSystem/Stream/ReadableStreamTrait.php',
    'Friday\FileSystem\Stream\StreamFactory' => __DIR__ . '/FileSystem/Stream/StreamFactory.php',
    'Friday\FileSystem\Stream\WritableStream' => __DIR__ . '/FileSystem/Stream/WritableStream.php',
    'Friday\FileSystem\Stream\WritableStreamTrait' => __DIR__ . '/FileSystem/Stream/WritableStreamTrait.php',

    'Friday\FileSystem\Eio\Adapter' => __DIR__ . '/FileSystem/Eio/Adapter.php',
    'Friday\FileSystem\Eio\ConstTypeDetector' => __DIR__ . '/FileSystem/Eio/ConstTypeDetector.php',
    'Friday\FileSystem\Eio\OpenFlagResolver' => __DIR__ . '/FileSystem/Eio/OpenFlagResolver.php',

    'Friday\FileSystem\Pthreads\Adapter' => __DIR__ . '/FileSystem/Pthreads/Adapter.php',
    'Friday\FileSystem\Pthreads\Call' => __DIR__ . '/FileSystem/Pthreads/Call.php',
    'Friday\FileSystem\Pthreads\Yarn' => __DIR__ . '/FileSystem/Pthreads/Yarn.php',


];